# Generated by Django 5.2.4 on 2025-08-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='qtdPaginas',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='disponivel',
            field=models.BooleanField(blank=True),
        ),
    ]
