# Generated by Django 5.2.4 on 2025-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_author_book_publisher_delete_autor_delete_livro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='cpnj',
        ),
        migrations.AddField(
            model_name='publisher',
            name='cnnj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
