# Generated by Django 5.2.4 on 2025-09-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_publisher_cpnj_publisher_cnnj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='cnnj',
            new_name='cnpj',
        ),
    ]
