# Generated by Django 5.2.4 on 2025-09-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_cnnj_publisher_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ano_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
