# Generated by Django 5.2.4 on 2025-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_book_ano_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ano_publicacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
