# Generated by Django 5.2.4 on 2025-10-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_book_ano_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ano_publicacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
