# Generated by Django 5.2.4 on 2025-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_book_ano_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='capa',
            field=models.CharField(default=' ', max_length=510),
            preserve_default=False,
        ),
    ]
